CREATE DATABASE OtpDB;
USE OtpDB;

-- Bảng Otp
CREATE TABLE Otp (
    OtpID INT PRIMARY KEY,
    Email VARCHAR(100),
    OtpCode VARCHAR(10),
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    ExpiredAt DATETIME,
    State BOOLEAN DEFAULT FALSE
);


